spring:
  data:
    neo4j:
      uri: bolt://localhost:11003
      username: neo4j
      password: supermarket
server:
  port: 8099
application:
  location:
    generation: false
    

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true