spring:
  application:
    name: insignis-cart
  data:
    mongodb:
      database: insignis-db
      port: 27017
      uri: mongodb://localhost
server:
  port: 8095
  

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true