spring:
  application:
    name: insignis-product
  data:
    mongodb:
      database: insignis-db
      port: 27017
      uri: mongodb://localhost
      auto-index-creation: false
server:
  port: 8086
application:
  service:
    supplier: http://insignis-supplier/supplier
    
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true