spring:
  application:
    name: insignis-product
  data:
    mongodb:
      database: insignis-db
      port: 27017
      uri: mongodb://localhost
      auto-index-creation: false
server:
  port: 8086
application:
  service:
    supplier: http://insignis-supplier/supplier